holoocean:
  holoocean_node:
    ros__parameters:
      draw_arrow: false
      show_viewport: true
      relative_path: true
        # scenario_path: '/home/ue4/ros2_ws/src/holoocean-ros/holoocean_main/config/blueROV.json'
      scenario_path: '/home/ue4/ros2_ws/src/holoocean-ros/holoocean_main/config/sonar_test.json'
      publish_commands: true
      # render_quality: 0
      
